### ISSUE TITLE
why it's too slow?

### ISSUE THREAD

**Issue by pylover** [realazthat/aiopg8000#1]
Please checkout the: 

http://pylover.dobisel.com/posts/aiopg-aiopg_sa-and-aiopg8000/

```

    [aiopg.sa]  Total time: 12.46s
    [aiopg]     Total time: 5.57s
    [aiopg8000] Total time: 40.83s
    [aiopg]     is 2.24x faster than [aiopg.sa]
    [aiopg]     is 7.33x faster than [aiopg8000]
    [aiopg.sa]  is 3.28x faster than [aiopg8000]
```

**Comment by realazthat** [comment]
Compare it to pg8000 as well.

I the reason might have something to do with the prepared statements and the latencies between sending the different values.

To test this you can use cursor.mogrify() to format the params first and time that. I've got a version of aiopg8000 that i never pushed that allows for non-prepared statements (pg8000 only allows prepared statements), if it is helpful, i can look into pushing it next week.

**Comment by pylover** [comment]
Thanks, i'll fix it.

**Comment by pylover** [comment]
The results are updated after using the `cursor.mogrify`. no differs:

http://pylover.dobisel.com/posts/aiopg-aiopg_sa-and-aiopg8000/

**Comment by realazthat** [comment]
@pylover ok I'll look into it on sunday

**Comment by pylover** [comment]
Thanks a lot bro.
